# Generated by Django 2.2.18 on 2021-02-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_contact'),
    ]

    operations = [
    ]
